import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from engine import Diagram

OUT = pathlib.Path(sys.argv[1]); OUT.mkdir(parents=True, exist_ok=True)
C = [70, 660, 1250, 1840]; W = 480            # four columns on a 2400-wide sheet


def save(d, name):
    (OUT / f"{name}.svg").write_text(d.svg(), encoding="utf-8")
    print("wrote", name, len(d.nodes), "nodes")


# =====================================================================================================  1 · CARBON
d = Diagram("1 · Carbon footprint estimator", "Engine: SCOPE (carbon/)  ·  Scope 1, 2, 3 with uncertainty, an ML gap-filler, abatement planning and fuel runway", 2400, 1700)
d.band(46, 168, 2308, 300, "A · MEASURE FROM ACTIVITY DATA")
d.band(46, 546, 2308, 300, "B · ESTIMATE WHEN THERE ARE NO METERS (MACHINE LEARNING)")
d.band(46, 956, 2308, 262, "C · PLAN: CUT, SCHEDULE, SURVIVE")
d.node("in1", "input", C[0], 220, W, ["Fuel: diesel L, petrol L, LPG kg,", "natural gas m³", "Grid electricity kWh, T&D loss", "Purchased spend, ₹ lakh by category"], "Site activity data")
d.node("f1", "data", C[1], 214, W, ["factors.py · scope3.py", "Fuel kg CO₂ per unit (IPCC, EPA)", "CEA v22 grid  0.675 kg/kWh", "EPA USEEIO v1.3 by NAICS, ₹85/US$"], "Emission factors")
d.node("c1", "model", C[2], 220, W, ["E1 = Σ Qi · EFi / 1000", "E2 = kWh/(1−L) · EFgrid / 1000", "E3 = Σ (Sj/85) · EFj / 1000"], "calculator.py")
d.node("m1", "model", C[3], 214, W, ["5,000 lognormal draws", "σ: fuel 5%, grid 8%, spend 50%", "P5 / P50 / P95 per scope", "variance share per factor"], "Monte Carlo")
d.edge("in1", "r", "f1", "l", "reads"); d.edge("f1", "r", "c1", "l", "factors"); d.edge("c1", "r", "m1", "l", "tonnes")

d.node("in2", "input", C[0], 604, W, ["sector, activity, turnover ₹ Cr,", "employees, renewable share, year"], "Company profile")
d.node("p2", "process", C[1], 604, W, ["S1 and S2 point estimate", "90% conformal interval", "out-of-distribution warnings"], "predict.py")
d.node("t2", "model", C[2], 590, W, ["Ridge (chosen) · LightGBM", "XGBoost · Random forest", "grouped CV by company, overfit audit", "cross-conformal 90% intervals"], "train.py (offline)")
d.node("ds", "data", C[3], 596, W, ["data_synth.py: 3,000 synthetic firms", "prepare_brsr.py: real BRSR adapter", "(real filings not yet used)"], "Training data")
d.edge("in2", "r", "p2", "l", "inputs"); d.edge("t2", "l", "p2", "r", "fitted"); d.edge("ds", "l", "t2", "r", "trains")

d.node("ab", "model", C[0], 1004, 760, ["levers: diesel → solar, green PPA, supplier engagement", "marginal abatement cost curve, ₹ per tCO₂e", "pathway 2020–2050 P10 / P50 / P90, 1.5 °C line"], "abatement.py")
d.node("rw", "model", 890, 1004, 540, ["stock, daily use, variability, delivery day", "P(fuel lasts), with and without saving", "effect of a late delivery"], "runway.py")
d.node("dp", "model", 1570, 1004, 750, ["weather.py: ERA5 hourly 2020–25 → forecast.py LightGBM 168 h", "milp.py: HiGHS, generator on/off, Willans fuel curve", "simulate.py: A rules · B naive · C trained forecast"], "Dispatch engine (dispatch_eval.py)")
d.edge("p2", "b", "ab", "t", "ML S1, S2", fb=0.2, via=[(C[1] + 240, 934), (C[0] + 152, 934)])
d.edge("m1", "r", "ab", "t", "S1 + S2 + S3 baseline", fb=0.55, via=[(2340, 302), (2340, 876), (C[0] + 418, 876)], lab_dx=-760, lab_dy=0)
d.edge("dp", "l", "rw", "r", "saving")
d.edge("dp", "t", "ab", "t", "saving to abatement", dashed=True, fb=0.9, fa=0.2, via=[(1570 + 150, 905), (C[0] + 684, 905)], lab_dx=-150)

d.node("api", "process", 70, 1290, 2250, ["JSON lines over stdin and stdout  ·  one long-lived Python worker, one process, tested code reused unchanged"], "api_worker.py")
d.node("ui", "output", 70, 1432, 2250, ["01 Calculator · 02 Estimator · 03 Compare · Report · 06 Abatement · 07 Dispatch · 09 Fuel runway"], "Polaris sheets")
d.edge("ab", "b", "api", "t", fa=0.25, fb=0.15); d.edge("rw", "b", "api", "t", fb=0.5); d.edge("dp", "b", "api", "t", fb=0.88)
d.edge("api", "b", "ui", "t")
save(d, "1-carbon-architecture")

# =====================================================================================================  2 · EARTH
d = Diagram("2 · Satellite imagery: deforestation and lake pollution", "Engine: Task3 (monitor/)  ·  Sentinel-2 L2A pairs → candidate regions in hectares → human review", 2400, 1500)
d.band(46, 168, 2308, 304, "A · GET TWO DATED SCENES ON ONE GRID")
d.band(46, 548, 2308, 330, "B · DETECT")
d.band(46, 954, 2308, 296, "C · REVIEW AND EXPORT")
d.node("src", "external", C[0], 214, W, ["Earth Search STAC catalogue", "catalog.py: search, cloud filter,", "fetch_pair → aligned 30 m grid"], "Sentinel-2 L2A")
d.node("up", "input", C[1], 218, W, ["8-band GeoTIFF pair, any CRS", "dates, scale, label", "size capped at 60 MB per file"], "User upload")
d.node("sc", "model", C[2], 214, W, ["Scene .npz: 8 bands + SCL mask", "validation, shared CRS and extent", "cloud and shadow pixels removed", "same clear support at every date"], "scenes.py")
d.node("ix", "process", C[3], 220, W, ["NDVI · NBR · NDMI", "NDWI · MNDWI", "NDCI (algae) · NDTI (turbidity)", "indices.py"], "Spectral indices")
d.edge("src", "t", "sc", "t", "fetched pair", via=[(C[0] + 240, 188), (C[2] + 240, 188)], fa=0.5, fb=0.5, lab_dx=-130); d.edge("up", "r", "sc", "l", "or upload"); d.edge("sc", "r", "ix", "l", "bands")

d.node("fm", "model", C[0], 612, W, ["16 features: index values and changes", "Random forest, 160 trees, seed 42", "spatial split: west 70% / east 30%", "6-column gap, Hansen GFC 2024 labels"], "Forest model (learning.py)")
d.node("nd", "process", C[1], 618, W, ["rule: NDVI drop ≥ threshold", "on pixels that were forest", "the baseline the model must beat"], "NDVI screening baseline")
d.node("wm", "model", C[2], 612, W, ["MNDWI threshold, or pretrained U-Net", "(Apache-2.0, tiled CPU inference)", "comparable water on clear pixels", "algae rise (NDCI), turbidity (NDTI)"], "Lake analysis")
d.node("hn", "data", C[3], 616, W, ["Hansen Global Forest Change v1.12", "canopy ≥ 30%, loss years excluded", "reference map, not field truth"], "Reference labels")
d.edge("ix", "b", "fm", "t", "features", via=[(C[3] + 240, 520), (C[0] + 240, 520)], fb=0.5)
d.edge("hn", "l", "wm", "r", "labels", dashed=True)
d.edge("ix", "b", "wm", "t", fa=0.2, fb=0.5, via=[(C[3] + 96, 540), (C[2] + 240, 540)])

d.node("rg", "model", C[0], 1010, W, ["connected patches, minimum size", "area in hectares, mean score", "map location of each region"], "workspace.py: regions")
d.node("rv", "process", C[1], 1010, W, ["status: needs review, confirmed,", "false positive, unclear, plus a note", "saved atomically, locked"], "Human review")
d.node("ex", "process", C[2], 1010, W, ["PNG layers, CSV queue, GeoJSON", "zip with summary and scene metadata", "RGB-only comparison, timeline"], "exports.py")
d.node("sw", "output", C[3], 1010, W, ["sat_worker.py, 4 threads, owner-scoped", "10 Forest loss · 11 Lake water", "13 Earth models"], "Polaris sheets")
d.edge("fm", "b", "rg", "t"); d.edge("nd", "b", "rg", "t", fb=0.72, fa=0.5, via=[(C[1] + 240, 926), (C[0] + 346, 926)], dashed=True)
d.edge("wm", "b", "rg", "t", fb=0.92, fa=0.5, via=[(C[2] + 240, 900), (C[0] + 442, 900)])
d.edge("rg", "r", "rv", "l"); d.edge("rv", "r", "ex", "l"); d.edge("ex", "r", "sw", "l")
d.note(70, 1330, "Result is screening for a person to review. It is never proof of deforestation, and lake figures are optical proxies, not concentrations.", fs=22, bold=True)
d.note(70, 1372, "Held-out forest F1: random forest 0.802 against 0.742 for the NDVI rule. Rondônia pair: 245.43 ha in 84 regions.", fs=22)
save(d, "2-satellite-architecture")

# =====================================================================================================  3 · MICROGRID
d = Diagram("3 · Micro-grid solar and wind optimisation", "Engines: netzero-ai (grid-tied site) and SCOPE dispatch (diesel polar and community sites)  ·  forecast → optimise → stress-test", 2400, 1500)
d.band(46, 168, 2308, 300, "A · DATA")
d.band(46, 548, 2308, 300, "B · FORECAST AND OPTIMISE")
d.band(46, 928, 2308, 300, "C · STRESS-TEST AND REPORT")
d.node("dd", "input", C[0], 214, W, ["generate_demo_data.py, seeded", "or PVGIS · Open-Meteo · UCI loaders", "clean_and_merge.py"], "Weather, solar, load")
d.node("ms", "data", C[1], 212, W, ["master_hourly.csv (hourly)", "solar, wind, load, price, carbon", "synthetic demo day, labelled"], "Dataset")
d.node("cf", "process", C[2], 218, W, ["solar 1,000 kW · wind 500 kW", "battery 2,000 kWh, 500 kW, 20–90%", "grid import 1,000 kW"], "config.yaml: the plant")
d.node("er", "external", C[3], 214, W, ["Open-Meteo ERA5 hourly 2020–2025", "polar and community profiles", "PV and wind physics, simulated demand"], "SCOPE dispatch inputs")
d.edge("dd", "r", "ms", "l"); d.edge("cf", "b", "lp", "t", "limits", fa=0.3, fb=0.3)

d.node("fc", "model", C[0], 600, W, ["features.py: lags, calendar, weather", "XGBoost × 3: solar, wind, load", "forecast_all(): 24 h ahead", "MAE 11.6 / 3.4 / 23.5 kW"], "Forecaster")
d.node("tf", "process", C[1], 612, W, ["time-of-day tariff ₹/kWh", "grid carbon intensity kg/kWh", "added to every forecast hour"], "Prices")
d.node("lp", "model", C[2], 590, W, ["Pyomo linear programme, HiGHS", "min cost + carbon + battery wear", "energy balance, SOC dynamics, limits", "soft end-of-day reserve"], "optimization/model.py")
d.node("fb", "process", C[3], 612, W, ["rule-based greedy dispatch", "used when no optimal plan exists", "result is labelled as a fallback"], "Fallback planner")
d.edge("ms", "b", "fc", "t", "history", fa=0.3, via=[(C[1] + 144, 520), (C[0] + 240, 520)])
d.edge("fc", "r", "tf", "l", "forecast"); d.edge("tf", "r", "lp", "l", "priced day"); d.edge("lp", "r", "fb", "l", "no feasible plan", dashed=True)
d.edge("er", "b", "lp", "t", "SCOPE: LightGBM 168 h + MILP", dashed=True, fb=0.8, via=[(C[3] + 240, 535), (C[2] + 384, 535)], lab_dx=-80)

d.node("sn", "model", C[0], 984, W, ["cloud event · wind drop · load spike", "battery low · grid outage", "same day, re-planned each time"], "scenarios.py")
d.node("kp", "process", C[1], 984, W, ["renewable used and spilled", "grid kWh, cost, CO₂", "unserved kWh, load coverage"], "KPIs")
d.node("sm", "model", C[2], 984, W, ["A rules · B naive forecast · C trained", "Economy, Green or Survival mode", "diesel litres, CO₂ t, unserved kWh"], "SCOPE simulate.py")
d.node("sv", "output", C[3], 984, W, ["07 Dispatch · 08 Micro-grid", "saving feeds abatement and runway", "analyst explains the plan"], "Polaris sheets")
d.edge("lp", "b", "sn", "t", fa=0.208, via=[(C[2] + 100, 890), (C[0] + 240, 890)]); d.edge("sn", "r", "kp", "l", "plan"); d.edge("kp", "r", "sm", "l", dashed=True); d.edge("sm", "r", "sv", "l")
d.edge("kp", "b", "sv", "b", via=[(C[1] + 240, 1170), (C[3] + 240, 1170)], dashed=False)
d.note(70, 1300, "Optimiser result: all five disturbances absorbed except a full grid outage, which sheds load and says so (4,889 kWh unserved).", fs=22, bold=True)
d.note(70, 1342, "Polar station on diesel: A 49,036 L, B 47,730 L, C 45,503 L a year, so planning ahead saves 7.2% and 9.5 t CO₂.", fs=22)
save(d, "3-microgrid-architecture")

# =====================================================================================================  4 · AIR
d = Diagram("4 · Localised greenhouse-gas forecasting", "Engine: task1 (src/)  ·  NOAA CarbonTracker CT2026 regional CO₂ → trained forecasts judged against a benchmark", 2400, 1500)
d.band(46, 168, 2308, 300, "A · DATA")
d.band(46, 548, 2308, 330, "B · TRAIN, FORECAST, JUDGE")
d.band(46, 954, 2308, 296, "C · ALERT AND REPORT")
d.node("no", "external", C[0], 214, W, ["NOAA GML CarbonTracker CT2026", "3-hourly pbl_co2, 3° × 2° cells", "nearest cell to Noida and Ahmedabad"], "Source")
d.node("fe", "process", C[1], 218, W, ["scripts/fetch_cities.py", "8 three-hourly values → one daily mean", "no interpolation, no invented offsets"], "Extraction")
d.node("cs", "data", C[2], 212, W, ["data/cities/*.csv", "manifest with sha256 per file", "checked on every read"], "City histories")
d.node("up", "input", C[3], 218, W, ["date, value, optional unit", "≥ 900 valid days over 3 years", "CO₂ ppm or CH₄ ppb"], "Optional sensor CSV")
d.edge("no", "r", "fe", "l"); d.edge("fe", "r", "cs", "l", "daily values"); d.edge("up", "l", "cs", "r", dashed=True)

d.node("sp", "process", C[0], 610, W, ["train 72% · calibration 14% · test 14%", "in time order, targets that cross", "a boundary are excluded"], "Chronological split")
d.node("ft", "model", C[1], 596, W, ["lag and rolling statistics, trend,", "annual cycle, forecast horizon", "causal forward fill of at most 3 days"], "forecast.py: features")
d.node("md", "model", C[2], 590, W, ["Seasonal Ridge · Lag Ridge", "Random forest", "benchmarks: persistence ×2", "auto-pick on calibration RMSE", "7, 14 or 30 days ahead"], "Models")
d.node("vd", "output", C[3], 596, W, ["90% band from calibration errors", "MAE, RMSE, coverage on the test period", "skill = 1 − MAE / MAE persistence"], "Verdict")
d.edge("cs", "b", "sp", "t", via=[(C[2] + 240, 520), (C[0] + 240, 520)]); d.edge("sp", "r", "ft", "l"); d.edge("ft", "r", "md", "l", "design matrix"); d.edge("md", "r", "vd", "l", "bands")

d.node("an", "process", C[0], 1010, W, ["mean + σ of the preceding 90 days", "flag if above the review level", "never a health warning"], "cities.py: review flags")
d.node("rp", "process", C[1], 1010, W, ["forecast CSV, portable HTML report", "analysis zip with checksums"], "reports.py")
d.node("sh", "output", C[2], 1010, W, ["04 Air forecast · 05 Air alerts", "red banner when the model loses", "Noida +15.5% · Ahmedabad −52.3%"], "Polaris sheets")
d.node("lm", "process", C[3], 1010, W, ["Groq-hosted model, figures only", "VERDICT line it may not contradict", "exact context shown on the sheet"], "Analyst")
d.edge("cs", "b", "an", "t", fa=0.15, fb=0.79, via=[(C[2] + 72, 505), (605, 505), (605, 928), (C[0] + 380, 928)], dashed=True)
d.edge("vd", "b", "sh", "t", fb=0.7, via=[(C[3] + 240, 915), (C[2] + 336, 915)]); d.edge("an", "r", "rp", "l", dashed=True); d.edge("rp", "r", "sh", "l", dashed=True); d.edge("sh", "r", "lm", "l", "ask")
d.note(70, 1330, "Data are real NOAA model estimates for a 3° × 2° cell, not a city sensor. The sheet states this and shows where the trained model loses.", fs=22, bold=True)
d.note(70, 1372, "Noida: 6.80 ppm holdout MAE against 8.05 for persistence (191 targets). Ahmedabad: 8.64 against 5.67, so persistence wins.", fs=22)
save(d, "4-air-forecast-architecture")

# =====================================================================================================  5 · FINAL FLOWCHART
d = Diagram("5 · Polaris end-to-end flowchart", "From a visitor's first click to a figure with its range, its limits and a record  ·  all four tasks, the safeguards and the decisions on the way", 2400, 2040)
d.band(46, 168, 2308, 232, "1 · VISITOR AND REQUEST")
d.band(46, 454, 2308, 232, "2 · SERVER GATE")
d.band(46, 740, 2308, 196, "3 · THE FOUR ENGINES")
d.band(46, 990, 2308, 452, "4 · JUDGE THE RESULT BEFORE SHOWING IT")
d.band(46, 1486, 2308, 170, "5 · SHOW ONLY WHAT BELONGS TO THE INPUTS")
d.band(46, 1702, 2308, 196, "6 · EXPLAIN AND ACT")

d.node("t1", "terminal", C[0], 224, W, ["Visitor opens Polaris"], "START")
d.node("p1", "process", C[1], 214, W, ["Next.js serves the sheet", "random token in an HttpOnly cookie;", "only its hash reaches the engines"], "Session")
d.node("i1", "input", C[2], 214, W, ["inputs, city, scenario or scene", "upload or fetched region", "5 sections, 15 sheets"], "Choose and enter")
d.node("d1", "decision", C[3] - 20, 196, W + 40, ["Input valid?"], None, h=170)
d.edge("t1", "r", "p1", "l"); d.edge("p1", "r", "i1", "l"); d.edge("i1", "r", "d1", "l")
d.edge("d1", "t", "i1", "t", "no: message shown, old inputs kept", dashed=True, via=[(C[3] + 240, 184), (C[2] + 240, 184)], lab_dx=-420)

d.node("p2", "process", C[0], 500, W, ["strict schema and size limits", "per-client and hourly quotas", "uploads capped at 60 MB a file"], "Route handler")
d.node("d2", "decision", C[1] - 20, 480, W + 40, ["Engine ready,", "queue under 24?"], None, h=170)
d.node("p3", "process", C[2], 500, W, ["identical in-flight calls share", "one answer; one JSON line goes", "to the engine's worker process"], "Dispatch")
d.node("e2", "external", C[3], 508, W, ["503 busy or 502 not ready", "60 s readiness deadline,", "unhealthy worker restarted"], "Refused in plain words")
d.edge("d1", "b", "p2", "t", "yes", via=[(C[3] + 240, 428), (C[0] + 240, 428)], lab_dx=-760)
d.edge("p2", "r", "d2", "l"); d.edge("d2", "r", "p3", "l", "yes")
d.edge("d2", "b", "e2", "b", "no", dashed=True, fa=0.5, via=[(C[1] + 240, 704), (C[3] + 240, 704)], lab_dx=-240)

d.node("en1", "model", C[0], 786, W, ["Monte Carlo, abatement,", "runway, ML gap-filler"], "Carbon")
d.node("en2", "model", C[1], 786, W, ["Ridge and forest", "against persistence"], "Air")
d.node("en3", "model", C[2], 786, W, ["forest model and NDVI rule,", "water mask, regions in ha"], "Earth")
d.node("en4", "model", C[3], 786, W, ["XGBoost forecast, HiGHS plan,", "five stress scenarios"], "Micro-grid")
d.edge("p3", "b", "en1", "t", fa=0.12, fb=0.5, via=[(C[2] + 58, 722), (C[0] + 240, 722)])
d.edge("p3", "b", "en2", "t", fa=0.3, fb=0.5, via=[(C[2] + 144, 730), (C[1] + 240, 730)])
d.edge("p3", "b", "en3", "t", fa=0.5, fb=0.5)
d.edge("p3", "b", "en4", "t", fa=0.88, fb=0.5, via=[(C[2] + 422, 738), (C[3] + 240, 738)])

d.node("p4", "process", C[0], 1070, W, ["P5 to P95 per scope,", "variance share per factor"], "Range with drivers")
d.node("d4", "decision", C[1] - 20, 1030, W + 40, ["Trained model beat", "its benchmark?"], None, h=190)
d.node("d5", "decision", C[3] - 20, 1030, W + 40, ["Optimal plan", "exists?"], None, h=190)
d.node("b1", "process", C[1], 1296, W, ["skill shown as a negative number", "red banner on the sheet", "the loss is not hidden"], "No: say so")
d.node("b2", "process", C[3], 1296, W, ["rule-based fallback plan", "labelled with the reason", "unserved load reported"], "No: fallback")
d.edge("en1", "b", "p4", "t"); d.edge("en2", "b", "d4", "t")
d.edge("en3", "b", "d4", "t", via=[(C[2] + 240, 962), (C[1] + 240, 962)])
d.edge("en4", "b", "d5", "t")
d.edge("d4", "b", "b1", "t", "no"); d.edge("d5", "b", "b2", "t", "no", dashed=True)

d.node("p5", "output", C[0], 1536, 2250, ["The result, its range, its source and its limits appear only if they belong to the inputs now on screen", "otherwise they are cleared and never paired with a stale value. Exports and print wait for a complete result."], "Show")
d.edge("p4", "b", "p5", "t", fb=(C[0] + 240 - 70) / 2250)
d.edge("b1", "b", "p5", "t", fb=(C[1] + 240 - 70) / 2250); d.edge("b2", "b", "p5", "t", fb=(C[3] + 240 - 70) / 2250)
d.edge("d4", "r", "p5", "t", "yes", fb=0.509, via=[(1215, 1125), (1215, 1500)], lab_dx=0)
d.edge("d5", "l", "p5", "t", "yes", fb=0.762, via=[(1785, 1125), (1785, 1500)], lab_dx=0)

d.node("d6", "decision", C[0], 1738, W, ["Ask the analyst?"], None, h=150)
d.node("p6", "process", C[1], 1744, W, ["figures frozen, VERDICT line added", "quota checked, Groq model explains", "answer marked stale if inputs change"], "Analyst")
d.node("p7", "output", C[2], 1750, W, ["export CSV, JSON, print, GeoJSON", "save a region review", "hand off to the Plan sheets"], "Act")
d.node("t2", "terminal", C[3], 1764, W, ["A figure with its range, its limits", "and a record"], "END")
d.edge("p5", "b", "d6", "t", fa=(C[0] + 240 - 70) / 2250)
d.edge("d6", "r", "p6", "l", "yes"); d.edge("p6", "r", "p7", "l"); d.edge("p7", "r", "t2", "l")
d.edge("d6", "b", "p7", "b", "no", dashed=True, via=[(C[0] + 240, 1912), (C[2] + 240, 1912)], lab_dx=-300)
save(d, "5-final-flowchart")
